### ISSUE TITLE
Missing VRT?

### ISSUE THREAD

**Issue by springmeyer** [mapbox/gdal-polygonize-test#1]
The test setup instructions show downloading a tif (https://github.com/mapbox/gdal-polygonize-test#running-the-test), but the test.sh looks like it also depends on a VRT. Can you share whether this should be downloaded as well or created on the fly?

**Comment by MateoV** [comment]
@springmeyer thanks for flagging. A VRT is indeed created when the test is run [here](https://github.com/mapbox/gdal-polygonize-test/blob/df20161a3d326d812d8f07f6292f6d3201a2a2ec/test.sh#L115), but the wrong variable was being used in the function.

**Comment by springmeyer** [comment]
thanks works for me now.
