### ISSUE TITLE
Parallel code doesn't polygonize all chunks

### ISSUE THREAD

**Issue by daaugusto** [mapbox/gdal-polygonize-test#3]
Hi,

Thank you for providing the useful script to speed up the polygonize process. I believe though there is an indexing bug in the Python code. The lines:

```
        for x in range(0, $(($XCHUNKS-1))):
            for y in range(0, $(($YCHUNKS-1))):
```

should read:

```
        for x in range(0, $(($XCHUNKS))):
            for y in range(0, $(($YCHUNKS))):
```
since `range` already iterates in `[a,b)`.

**Comment by sgillies** [comment]
@daaugusto thanks for pointing this out. This project is, however, finished.
